preload=$HOME/.local/bin/lethetux.png
preload=$HOME/.local/bin/lethethread.png
preload=$HOME/.local/bin/lethefish.png
preload=$HOME/.local/bin/lethemind.png
preload=$HOME/.local/bin/lethepunk.png

wallpaper {
    monitor = HDMI-A-1
    path = /home/alexandre/.local/share/wallpapers/lethetux.png
    fit_mode = cover
}

ipc = true
splash = false
