shell	fish

font_family	Lilex Nerd Font
bold_font	auto
italic_font	auto
bold_italic_font	auto
font_size	14.0

background	#202020
foreground 	#d7d7d7

map ctrl+shift+c	copy_to_clipboard
map ctrl+c	interrupt
map ctrl+shift+v	paste_from_clipboard

map shift+right	next_tab
map shift+left	previous_tab
map ctrl+shift+t new_tab
map ctrl+shift+w close_tab
map ctrl+shift+e open_url_with_hints
map ctrl+shift+f11 toggle_fullscreen
map ctrl+shift+l next_layout

tab_bar_style	powerline
tab_activity_symbol !
active_tab_foreground   #e9e9e9
active_tab_background   #1c2057
active_tab_font_style   bold
inactive_tab_foreground #b9b9b9
inactive_tab_background #242424
inactive_tab_font_style normal

